### ISSUE TITLE
Gradle 2.2 cannot call super.getJrubyVersion() properly

### ISSUE THREAD

**Issue by rtyler** [jruby-gradle/jruby-gradle-storm-plugin#26]
Working with the pre-release version of 0.4.0, and [this line](https://github.com/jruby-gradle/jruby-gradle-storm-plugin/blob/27ec0761d01d9685c094009f79abad1033e0f95d/src/main/groovy/com/github/jrubygradle/storm/internal/JRubyStormJar.groovy#L24) doesn't seem to want to cooperate

@ysb33r this ring any bells?  :/

```
Caused by: groovy.lang.MissingMethodException: No signature of method: com.github.jrubygradle.storm.internal.JRubyStormJar_Decorated.getJrubyVersion() is applicable for argument types: () values: []
Possible solutions: getJrubyVersion(), getJrubyVersion(), getJrubyVersion(), jrubyVersion(java.lang.String), getVersion(), getJrubyMainsVersion()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at com.github.jrubygradle.storm.internal.JRubyStormJar.getJrubyVersion(JRubyStormJar.groovy:24)
        at com.github.jrubygradle.storm.internal.JRubyStormJar_Decorated.getJrubyVersion(Unknown Source)
        at com.github.jrubygradle.jar.JRubyJar.addJRubyDependency(JRubyJar.groovy:209)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by ysb33r** [comment]
First guess would be that you compiled for a post 2.4 gradle version and was trying to run against and older version.

**Comment by rtyler** [comment]
@ysb33r oh brother, I didn't realize there was any fundamental differences in generated output for Groovy 2.x versions.

Aside from just adding the compile time dependency to the right version of Groovy in a `build.gradle` is there any other means of pinning that version?

I should note that this issue only manifests on Gradle 2.2, not 2.0, 2.4 or 2.6

**Comment by ysb33r** [comment]
Gradle 2.2 is indeed the culprit. There was binary change in the Jar class when they moved it from a Groovy implementation to a Java one. It was corrected in a subequent release, but 2.2 remains an issue.

**Comment by rtyler** [comment]
@ysb33r Bugger; I think the best course of action is to work around the issue and now call super on the property, does that make sense to you?

**Comment by ysb33r** [comment]
If that solves it, so be it. Pragmatism before purism.
